version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10.

jobs:
  build:
    working_directory: ~/turing/3module/projects/rails-engine
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: rails-engine
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: rails-engine
          POSTGRES_DB: rails-engine_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout

      - run: gem install bundler

      - run: bundle install

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rails db:setup

      - run: bundle exec rspec

workflows:
  version: 2.1
  integration:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
