version: 2.1

executors:
  default:
    working_directory: ~/turing/3module/projects/rails-engine
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: gcunningham
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: rails-engine_test
          POSTGRES_USER: gcunningham

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
        name: RSpec
        command: |
          bundle exec rspec
      - store_artifacts:
        path: coverage
      - persist_to_workspace:
          root: ~/turing/3module/projects/
          paths:
            - ./rails-engine

workflows:
  version: 2
  integration:
    jobs:
      - build
